name: Lighthouse CI
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * *" # every day at 5 AM
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse Sitemap
        id: sitemap-urls
        uses: tcarrio/sitemap-urls-extractor@v1.0.0
        with:
          sitemap-url: "https://www.eearomatics.com/sitemap.xml"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: "${{ steps.sitemap-urls.outputs.urls }}"
          uploadArtifacts: true
          temporaryPublicStorage: true
